# Generated by Django 4.2.2 on 2023-09-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
