# Generated by Django 4.2.2 on 2023-09-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='desc',
            field=models.TextField(default=22),
            preserve_default=False,
        ),
    ]
