# Generated by Django 4.2.2 on 2023-09-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_country_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Branch',
        ),
    ]
