# Generated by Django 4.2.2 on 2023-09-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_rename_country_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='Branch',
        ),
    ]
